### ISSUE TITLE
Add new scripts similar to this script

### ISSUE THREAD

**Issue by meet7202** [meet7202/Facebook-profile-pic-downloader#1]
We have seen many quizzes available on facebook. so we will try to make similar things on terminal by python scripts using [Graph API](https://developers.facebook.com/docs/graph-api/) and python libraries.
For this repository I would like you guys to explore more on [https://developers.facebook.com/docs/graph-api/overview](https://developers.facebook.com/docs/graph-api/overview)  and try to make different quizzes by yourself and try to make scripts to solve that fun quizzes by social chart of individual person.

**Comment by keshavg2** [comment]
i got my token and run the  program but nothing happened what is the issue i didn't understand can you help how to do it correctly??

**Comment by TheVzard** [comment]
After the update of Graph API to version 2 , you only get access to the profile of your friends who are using it. So it might be a possibility that none of your friends have installed this.
 
![msg](https://user-images.githubusercontent.com/22577662/34952756-d0512814-fa40-11e7-9782-e4a6295e4db3.PNG)

**Comment by chiragchevli** [comment]
Hello Owner...
I am Chirag Chevli(DAIICT) and want to contribute to Your Repository(Facebook-profile-pic-downloader).
Here is my Linked In Account Link (https://www.linkedin.com/in/chiragchevli/)
can u guide from Where Should I Start? #DWOC

**Comment by meet7202** [comment]
@17bcs029  & @TheVzard  The thing you guys are asking is completely valid as new version of Graph API just returns 25 objects in one JSON and returns you a next JSON page link so that you can access next 25 objects from next JSON and so on. previously they were returning whole list ( can say even 5000 objects which includes almost all friends) (that JSON limit itself shows facebook friend list limit :) ) .

You can find this issue here : [Stackoverflow](https://stackoverflow.com/questions/10406990/facebook-graph-api-friends-request-now-only-returning-25-friends-per-page-wha)
PS : You will find solution itself on same page also :p

You can also see JSON in browser by visiting : https://graph.facebook.com/me/friends?access_token=token_here

Try to see JSON and if you are getting whole list by single JSON request change that link in code and send me a pull request. I will surely merge that :)

Best of Luck and Keep Improving.

**Comment by meet7202** [comment]
@chiragchevli try to explore more on [https://developers.facebook.com/docs/graph-api/overview](https://developers.facebook.com/docs/graph-api/overview) and try to understand the logic of script and also see the JSON list in browser so you can understand that by providing different permissions by facebook user how can we get their public data on JSON list and then manipulating with that data is all we have to do :)

Best of Luck ! Keep Improving.
